AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: NYCInfo Tours - Serverless backend (HTTP API + Lambda + DynamoDB + SES)

Globals:
  Function:
    Runtime: nodejs20.x
    Timeout: 10
    MemorySize: 256
    Environment:
      Variables:
        APPLICATIONS_TABLE: !Ref ApplicationsTable
        BOOKINGS_TABLE: !Ref BookingsTable
        SES_FROM_EMAIL: no-reply@nycinfotours.app

Resources:
  HttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      CorsConfiguration:
        AllowHeaders:
          - Content-Type
        AllowMethods:
          - POST
          - OPTIONS
        AllowOrigins:
          - '*'

  ApplicationsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NYCInfoApplications
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: applicationId
          AttributeType: S
      KeySchema:
        - AttributeName: applicationId
          KeyType: HASH

  BookingsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: NYCInfoBookings
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: bookingId
          AttributeType: S
      KeySchema:
        - AttributeName: bookingId
          KeyType: HASH

  CreateApplicationFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: applications.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ApplicationsTable
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      Events:
        PostApplications:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /applications
            Method: POST

  CreateBookingFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: src/
      Handler: bookings.handler
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref BookingsTable
        - Statement:
            - Effect: Allow
              Action:
                - ses:SendEmail
                - ses:SendRawEmail
              Resource: '*'
      Events:
        PostBookings:
          Type: HttpApi
          Properties:
            ApiId: !Ref HttpApi
            Path: /bookings
            Method: POST

Outputs:
  ApiUrl:
    Description: Base URL for the HTTP API (use this as window._config.api.invokeUrl)
    Value: !Sub "https://${HttpApi}.execute-api.${AWS::Region}.amazonaws.com"
